version: '3.4'

services:      
  db:
    image: mariadb:10.3.16
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_DATABASE=greetings
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=1234
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/:ro
  myservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=db
      - DATABASE_DB=greetings
      - DATEBASE_USER=dbuser
      - DATABASE_PASSWORD=1234

